<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/modules.php 
 * 
 * Contao extension: gallery_creator 4.8.0 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['0'] = "Portfolio-Manager";
$GLOBALS['TL_LANG']['MOD']['gallery_creator']['1'] = "Portfolios erstellen und bearbeiten.";
$GLOBALS['TL_LANG']['FMD']['fmd_type_gallery_creator'] = "Portfolio";
$GLOBALS['TL_LANG']['FMD']['gallery_creator_fmd']['0'] = "Portfolio-Frontend-Modul";
$GLOBALS['TL_LANG']['FMD']['gallery_creator_fmd']['1'] = "Portfolios als Frontend-Modul einbinden.";
$GLOBALS['TL_LANG']['CTE']['ce_type_gallery_creator'] = "Portfolio";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_ce']['0'] = "Portfolio-Inhaltselement";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_ce']['1'] = "Portfolios als Inhaltselement einbinden.";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_ce_news']['0'] = "Portfolio-News-Inhaltselement";
$GLOBALS['TL_LANG']['CTE']['gallery_creator_ce_news']['1'] = "Ein Portfolio im Newsbeitrag anzeigen lassen.";

$GLOBALS['TL_LANG']['FMD']['scheduler'] = "Cron/Scheduler";
$GLOBALS['TL_LANG']['FMD']['start_scheduler']['0'] = "Scheduler im FE per Ajax auslösen";
$GLOBALS['TL_LANG']['FMD']['start_scheduler']['1'] = "Beim Aufruf des Frontends wird die Cron Erweiterung per Ajax aufgerufen.";


?>