<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_content.php 
 * 
 * Contao extension: gallery_creator 4.8.0 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_content']['pagination_legend'] = "Pagination Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['miscellaneous_legend'] = "Allgemeine Einstellungen";
$GLOBALS['TL_LANG']['tl_content']['album_listing_legend'] = "Einstellungen für die Portfolioauflistung";
$GLOBALS['TL_LANG']['tl_content']['picture_listing_legend'] = "Einstellungen für die Bildauflistung (Detailansicht)";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['0'] = "Vorschaubilder pro Reihe";
$GLOBALS['TL_LANG']['tl_content']['gc_rows']['1'] = "Wählen Sie die Anzahl Vorschaubilder pro Reihe aus. (0=So viele wie möglich)";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['0'] = "Lediglich folgende Portfolios im Frontend anzeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_albums']['1'] = "Ausgewählte Portfolios werden im Frontend angezeigt.";
$GLOBALS['TL_LANG']['tl_content']['gc_publish_all_albums']['0'] = "Alle angelegten Portfolios im Frontend zeigen";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['0'] = "Portfolio-Template";
$GLOBALS['TL_LANG']['tl_content']['gc_template']['1'] = "Hier können Sie das Portfolio-Template auswählen.";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['0'] = "Ajax-Thumb-Slider aktivieren";
$GLOBALS['TL_LANG']['tl_content']['gc_activateThumbSlider']['1'] = "Ajax-Thumb-Slider bei mouseover in der Portfolioübersicht aktivieren?";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['0'] = "Weiterleitung bei einzelnem Portfolio";
$GLOBALS['TL_LANG']['tl_content']['gc_redirectSingleAlb']['1'] = "Soll, wenn nur ein Portfolio ausgewählt wurde, automatisch zur Detailansicht weitergeleitet weden?";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['0'] = "Anzahl Portfolios pro Seite in der Portfolioübersicht";
$GLOBALS['TL_LANG']['tl_content']['gc_AlbumsPerPage']['1'] = "Die Anzahl an Portfolios pro Seite in der Portfolioübersicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['0'] = "Anzahl Bilder pro Seite in der Detailansicht";
$GLOBALS['TL_LANG']['tl_content']['gc_ThumbsPerPage']['1'] = "Anzahl Bilder pro Seite in der Detailansicht. Geben Sie 0 ein, um den automatischen Seitenumbruch zu deaktivieren.";
$GLOBALS['TL_LANG']['tl_content']['gc_PaginationNumberOfLinks']['0'] = "Anzahl Links in der Pagination Navigation";
$GLOBALS['TL_LANG']['tl_content']['gc_PaginationNumberOfLinks']['1'] = "Legen Sie die Anzahl Links in der Pagination Navigation fest. Standardwert ist 7.";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['0'] = "Sortierung der Portfolios";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting']['1'] = "Nach welchem Feld sollen die Portfolios im Frontend sortiert werden?";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['0'] = "Sortierrichtung";
$GLOBALS['TL_LANG']['tl_content']['gc_sorting_direction']['1'] = "DESC: absteigend, ASC: aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['0'] = "Sortierung der Bilder";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting']['1'] = "Nach welchem Feld sollen die Bilder in einem einzelnen Portfolio im Frontend sortiert werden?";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['0'] = "Sortierrichtung";
$GLOBALS['TL_LANG']['tl_content']['gc_picture_sorting_direction']['1'] = "DESC: absteigend, ASC: aufsteigend";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['0'] = "Detailansicht: Thumbnailbreite und Thumbnailhöhe";
$GLOBALS['TL_LANG']['tl_content']['gc_size_detailview']['1'] = "Hier können Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_detailview']['0'] = "Detailansicht: Bildabstand";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_detailview']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['0'] = "Portfolioauflistung: Thumbnailbreite und Thumbnailhöhe";
$GLOBALS['TL_LANG']['tl_content']['gc_size_albumlisting']['1'] = "Hier können Sie die Abmessungen des Bildes und den Skalierungsmodus festlegen.";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_albumlisting']['0'] = "Portfolioauflistung: Bildabstand";
$GLOBALS['TL_LANG']['tl_content']['gc_imagemargin_albumlisting']['1'] = "Hier können Sie den oberen, rechten, unteren und linken Bildabstand eingeben.";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['0'] = "Großansicht/Neues Fenster";
$GLOBALS['TL_LANG']['tl_content']['gc_fullsize']['1'] = "Großansicht des Bildes in einer Lightbox bzw. den Link in einem neuem Browserfenster öffnen.";
 
?>
