<?php
/**
 * TL_ROOT/system/modules/gallery_creator/languages/de/tl_gallery_creator_albums.php 
 * 
 * Contao extension: gallery_creator 4.8.0 
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Marko Cupic 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Marko Cupic (markocupic) 
 * Translator: Marko Cupic (markocupic) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['album_info'] = "Portfolioinformationen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['protection'] = "Portfolio vor Frontendzugriff schützen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['upload_settings'] = "Bildeinstellungen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['insert_article'] = "Artikel vor oder nach dem Portfolio einfügen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['uploader_legend'] = "Uploader";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['maintenance'] = "Datenbank-Tabellen bereinigen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['album_preview_thumb_legend'] = "Vorschau-Thumbnail-Einstellungen & Sortierreihenfolge";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['id']['0'] = "Portfolio-ID";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['alias']['0'] = "Portfolioalias";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['alias']['1'] = "Der Portfolioalias ist zugleich auch Verzeichnisnamen der Bilder eines Portfolios";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['published']['0'] = "Portfolio veröffentlichen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['date']['0'] = "Erstellungsdatum";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['displ_alb_in_this_ce']['0'] = "Dieses Portfolio in folgenden \"gallery_creator\" Inhaltselementen anzeigen lassen:";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['owner']['0'] = "Besitzer/Ersteller";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['event_location']['0'] = "Veranstaltungsort";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['description']['0'] = "Meta-Beschreibung der Seite";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['description']['1'] = "Hier können Sie eine kurze Beschreibung der Seite eingeben, die von Suchmaschinen wie Google oder Yahoo ausgewertet wird. Suchmaschinen indizieren normalerweise zwischen 150 und 300 Zeichen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['keywords']['0'] = "Suchbegriffe";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['keywords']['1'] = "Hier können Sie eine kommagetrennte Liste von Suchbegriffen eingeben. Suchbegriffe sind jedoch für die meisten Suchmaschinen (inklusive Google) nicht mehr relevant.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['name']['0'] = "Portfolioname";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['owners_name']['0'] = "Portfoliobesitzer";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['comment']['0'] = "Portfoliounterschrift/Beschreibungstext";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['thumb']['0'] = "Vorschau-Thumbnail und Sortierreihenfolge";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['thumb']['1'] = "Welches Bild soll in der Vorschau/Portfolioübersicht gezeigt werden?";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['protected']['0'] = "Portfolio schützen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['groups']['0'] = "Berechtigte Frontend-Gruppen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['insert_article_pre']['0'] = "Optional einen Artikel vor dem Portfolio einfügen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['insert_article_pre']['1'] = "Fügen Sie die ID des Artkels, den Sie optional in der Detailansicht vor dem Portfolio angezeigt haben möchten, ein.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['insert_article_post']['0'] = "Optional einen Artikel nach dem Portfolio einfügen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['insert_article_post']['1'] = "Fügen Sie die ID des Artkels, den Sie optional in der Detailansicht nach dem Portfolio angezeigt haben möchten, ein.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['fileupload']['0'] = "Datei-Upload";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['fileupload']['1'] = "Durchsuchen Sie Ihren Computer und wählen Sie die Dateien, die Sie auf den Server übertragen möchten.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['uploader']['0'] = "Uploader";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['uploader']['1'] = "Bitte wählen Sie zwischen den verschiedenen Datei-Uploadern aus.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_resolution']['0'] = "Bildbreite in Pixeln";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_resolution']['1'] = "Die Auflösung des Bildes wird während des Uploadvorganges auf folgenden Wert skaliert.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_quality']['0'] = "Bildqualität/Kompressionsrate";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['img_quality']['1'] = "Das Bild wird während des Uploadvorganges komprimiert. (100 = beste Qualität)";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['preserve_filename']['0'] = "Original-Dateinamen beibehalten";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['preserve_filename']['1'] = "Alternativ wird der Dateinamen vom System automatisch generiert.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['visitors']['0'] = "Anzahl Portfoliozugriffe";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['visitors_details']['0'] = "Besucher-Details (IP, Browserdetails, Zugriffszeit, etc.)";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['sortBy']['0'] = "Sortieren nach";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['sortBy']['1'] = "Bitte wählen Sie eine Sortierreihenfolge aus.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['assignedDir']['0'] = "Zugewiesenes Upload Verzeichnis";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['assignedDir']['1'] = "Neue Bilder werden vom Uploader in das gewählte Verzeichnis hochgeladen.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['new']['0'] = "Neues Portfolio";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['new']['1'] = "Ein neues Portfolio anlegen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['list_pictures']['0'] = "Portfolioinhalt auflisten";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['list_pictures']['1'] = "Bilder des Portfolios mit ID %s auflisten.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['edit_album']['0'] = "Portfolio bearbeiten";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['edit_album']['1'] = "Portfolio mit ID %s bearbeiten.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['delete']['0'] = "Portfolio löschen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['delete']['1'] = "Portfolio mit ID %s löschen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['toggle']['0'] = "Portfolio veröffentlichen/unveröffentlichen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['toggle']['1'] = "Portfolio ID %s veröffentlichen/unveröffentlichen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['upload_images']['0'] = "Bilder auf Server uploaden";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['upload_images']['1'] = "Dem Portfolio mit ID %s Bilder mittels Dateiupload hinzufügen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['import_images']['0'] = "Bilder vom Server ins Portfolio einlesen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['import_images']['1'] = "Bilder aus Verzeichnis auf Server ins Portfolio mit ID %s einlesen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['cut']['0'] = "Portfolio verschieben";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['cut']['1'] = "Portfolio mit ID %s verschieben";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteafter']['0'] = "Einfügen nach";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteafter']['1'] = "Einfügen nach Portfolio mit ID %s";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteinto']['0'] = "Einfügen in";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['pasteinto']['1'] = "Einfügen in Portfolio mit ID %s";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['reference']['displ_alb_in_this_ce'] = "Inhaltselement mit id=%s in Artikel \"%s\" auf Seite \"%s\"";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['reference']['no_scaling'] = "Bilder vor dem Upload nicht skalieren.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['name_asc'] = "Dateiname (aufsteigend)";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['name_desc'] = "Dateiname (absteigend)";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['date_asc'] = "Datum (aufsteigend)";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['date_desc'] = "Datum (absteigend)";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['custom'] = "Individuelle Reihenfolge";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['messages']['revise_database'] = "Datenbank bereinigen: Beschädigte/ungültige/verwaiste Datenbankeinträge entfernen ";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['revise_tables']['0'] = "Datenbank bereinigen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['revise_tables']['1'] = "Alte/fehlerhafte Datenbankeinträge löschen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['reviseTablesBtn']['0'] = "Datenbank bereinigen";

// new
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['observeAssignedDir']['0'] = "Upload Verzeichnis auf neue Bilder überwachen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['observeAssignedDir']['1'] = "Bei aktivierter Checkbox wird das zugeordnete Upload-Verzeichnis per Cron auf neue Bilddateien überwacht, welche automatisch in die Datenbank eingelesen werden.";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['deleteOrphanedDatarecords']['0'] = "Bilddatensätze ohne zugehörige Datei aus der Datenbank löschen";
$GLOBALS['TL_LANG']['tl_gallery_creator_albums']['deleteOrphanedDatarecords']['1'] = "Bei aktivierter Checkbox wird geprüft, ob für den Datensatz auch eine Datei auf dem Server vorhanden ist. Wenn nein, wird der Datensatz per Cron aus der Db gelöscht.";
?>